name: sponsors

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  
  push:
    branches: [ main ]

jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: pnpm
      - run: pnpm install
      - run: pnpm run build
        env:
          SPONSORKIT_AFDIAN_USER_ID: ${{ secrets.SPONSORKIT_AFDIAN_USER_ID }}
          SPONSORKIT_AFDIAN_TOKEN: ${{ secrets.SPONSORKIT_AFDIAN_TOKEN }}

      - name: Commit and push if changes are made
        run: |
          git config --global user.email "734243792@qq.com"
          git config --global user.name "FliPPeDround"
          git add -A
          git commit -m "chore: update deps" || echo "No changes to commit"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          commit-message: 'chore: update sponsors'
          title: 'chore: update sponsors'
          body: Update sponsors
          branch: chore/update-sponsors
          delete-branch: true
          base: main
